{"name": "Проверка неуспешной авторизации с невалидными данными", "status": "passed", "parameters": [{"name": "user_data", "value": "{'password': 'password', 'name': 'Username'}"}], "start": 1732195321970, "stop": 1732195323083, "uuid": "3271b7dd-0d08-4e37-b84b-ffc39ec77e82", "historyId": "0d7eac89450ac66f7e3bcd5e7956cce2", "testCaseId": "c624507b88d3811eb3f5ad3f0dbfed58", "fullName": "tests.test_login_user.TestLoginUser#test_autorization_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-APHBTB3O"}, {"name": "thread", "value": "6168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}